### ISSUE TITLE
Print Error

### ISSUE THREAD

**Issue by wuming123** [zzzz465/Rimworld-automatic-mod-sorter#3]
urllib.error.URLError: <urlopen error no host given>

what??
i use it for fist

**Comment by wuming123** [comment]
Rimworld_mod_sorter.exe
Traceback (most recent call last):
  File "Rimworld_mod_sorter.py", line 50, in <module>
  File "downloader.py", line 15, in download_DB
  File "urllib\request.py", line 222, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 543, in _open
  File "urllib\request.py", line 503, in _call_chain
  File "urllib\request.py", line 1360, in https_open
  File "urllib\request.py", line 1282, in do_open
urllib.error.URLError: <urlopen error no host given>
[4556] Failed to execute script Rimworld_mod_sorter

**Comment by zzzz465** [comment]
Please download the newer version. if you still get a bug, then re-open a issue
