### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by jackusm** [zzzz465/Rimworld-automatic-mod-sorter#6]
`Traceback (most recent call last):
  File "main.py", line 54, in <module>
  File "core\Modmanager.py", line 200, in setinit
  File "core\RWmanager.py", line 16, in LoadXML
  File "xml\etree\ElementTree.py", line 1197, in parse
  File "xml\etree\ElementTree.py", line 587, in parse
FileNotFoundError: [Errno 2] No such file or directory: '\\\\AppData\\LocalLow\\Ludeon Studios\\RimWorld by Ludeon Studios\\Config\\ModsConfig.xml'
[8412] Failed to execute script main`

**Comment by SkyeErnst** [comment]
I'm having this same issue. Using version v0.53Hotfix, traceback is as follows:

Traceback (most recent call last):
  File "main.py", line 54, in <module>
  File "core\Modmanager.py", line 200, in setinit
  File "core\RWmanager.py", line 16, in LoadXML
  File "xml\etree\ElementTree.py", line 1197, in parse
  File "xml\etree\ElementTree.py", line 587, in parse
FileNotFoundError: [Errno 2] No such file or directory: '\\Users\\Skye\\AppData\\LocalLow\\Ludeon Studios\\RimWorld by Ludeon Studios\\Config\\ModsConfig.xml'
[15632] Failed to execute script main

**Comment by zzzz465** [comment]
Fixed. download v0.55 version
thank you for your report!
