### ISSUE TITLE
Issue when using the program.

### ISSUE THREAD

**Issue by Emeranthil** [zzzz465/Rimworld-automatic-mod-sorter#8]
My version of the game is a DRM free version. I did not get it through Steam and it was custom installed in it's own spot instead of auto installed. I can make it see both of the things it needs to see, but when it tries to go past that it instead outputs this message and requires me to close the program. I've run as Admin as well as reinstalled the program. Neither have changed anything.

Traceback (most recent call last):
  File "main.py", line 63, in <module>
  File "core\Modmanager\Modmanager.py", line 213, in setinit
  File "core\Modmanager\Modmanager.py", line 55, in LoadMod
FileNotFoundError: [WinError 3] The system cannot find the path specified: ''
[6256] Failed to execute script main﻿

**Comment by zzzz465** [comment]
check v0.57 release and please commit below.

**Comment by dragonlance88** [comment]
having the exact same error come up when I try to input the mods folder (not workshop) at the initial popup, with both v0.57 and v0.56 releases. something that didn't happen with your older versions (v0.43)

**Comment by zzzz465** [comment]
I'll put checking method to get proper folder path.

**Comment by zzzz465** [comment]
can you upload full log via copying terminal?

**Comment by dragonlance88** [comment]
22:10:58 [INFO] : Initializing program...
22:10:58 [INFO] : fetching latest DB file from server...
22:10:58 [INFO] : please allow firewall internet connection.
22:10:59 [INFO] : DB download complete!
22:10:59 [INFO] : support for DRM-free version.
22:11:03 [INFO] : current version = 0.57
22:11:03 [INFO] : DB MOD COUNT : 795
22:11:03 [INFO] : Latest DB updated date : Sun Mar 24 22:37:59 2019
22:11:05 [INFO] : Active mod list loaded.
22:11:05 [INFO] : current active mod number = 153
22:12:43 [INFO] : Local mod path "C:/"
Load Workshop Mod? Y/N > n
Traceback (most recent call last):
  File "main.py", line 63, in <module>
  File "core\Modmanager\Modmanager.py", line 213, in setinit
  File "core\Modmanager\Modmanager.py", line 55, in LoadMod
FileNotFoundError: [WinError 3] The system cannot find the path specified: ''
[200] Failed to execute script main
Press any key to continue . . .

{[ It happens the same way no matter what folder I choose too :( ]}

**Comment by Emeranthil** [comment]
I was only just now able to get back to this thread as I was busy with other things. Sorry it took so long! I downloaded the new folder and tried to use it but I can't get it to work like the older one did. All the command prompts from the scripts just close instantly. Am I doing something wrong?

**Comment by zzzz465** [comment]
default path selected to C:/ weird.... are you sure you select Mods folder in Rimworld?

**Comment by zzzz465** [comment]
oh wait, give me a min

**Comment by Kite1024** [comment]
I'm having the same issue with the RAMS.v0.57.unstable release I've just downloaded. Below is my log (as far as I've seen equal to the one posted above).

I've tried using it on the RimWorld2150Win64 release which I've downloaded from SendOwl (original distribution channel for the non-steam version).

EDIT: I noticed it not asking for the ModConfig.xml, does it auto-detect this? It immediately asked for the Rimworld Local mod 'Mods' folder, which I gave.

EDIT2: In modmanager.py it tries to load the workshop location, which seems to be causing the error. Inside the LoadMod instance the 'if dir1 == None' does not seem to evaluate properly. My wild guess is that it _might_ help to change it to 'if dir1 is None', which would not be dependent on the dir1.eq method. Otherwise I wouldn't know either :(

===LOG===

11:02:59 [INFO] : Initializing program...
11:03:00 [INFO] : fetching latest DB file from server...
11:03:00 [INFO] : please allow firewall internet connection.
11:03:01 [INFO] : DB download complete!
11:03:01 [INFO] : support for DRM-free version.
11:03:04 [INFO] : current version = 0.57
11:03:05 [INFO] : DB MOD COUNT : 795
11:03:05 [INFO] : Latest DB updated date : Sun Mar 24 22:37:59 2019
11:03:07 [INFO] : Active mod list loaded.
11:03:07 [INFO] : current active mod number = 1
11:03:20 [INFO] : Local mod path "C:/Users/Nick/Downloads/QBit/gms/RimWorld/RimWorld2150Win64/Mods"
Load Workshop Mod? Y/N > N
Traceback (most recent call last):
  File "main.py", line 63, in <module>
  File "core\Modmanager\Modmanager.py", line 213, in setinit
  File "core\Modmanager\Modmanager.py", line 55, in LoadMod
FileNotFoundError: [WinError 3] Het systeem kan het opgegeven pad niet vinden: ''
[7120] Failed to execute script main
Press any key to continue . . .

===END===

**Comment by zzzz465** [comment]
I was busy for a while.
anyway, you're right! string value '' (blank) should be changed to 'None' type. but I think I forget about it.
download v0.571 version and please comment below!

https://github.com/zzzz465/Rimworld-automatic-mod-sorter/releases/tag/v0.571

**Comment by Emeranthil** [comment]
Alright. So It did actually run it after downloading the hotfix. It did also actually try to sort the mods, however it ran into another error/issue. I am unsure if this is an issue that is my fault or not haha. I love the speed of the program however. Thanks for addressing things so quickly by the way!

15:36:58 [INFO] : ---LOG START---
15:36:58 [INFO] : Floor Lights - 1.0
15:36:58 [INFO] : [SS]GhostArmy
15:36:58 [INFO] : Mechalit Core 1.0
15:36:59 [INFO] : Mechalit Equipment + Faction 1.0
15:36:59 [INFO] : 【ZP】Sengoku period
--- Logging error ---
Traceback (most recent call last):
  File "logging\__init__.py", line 1037, in emit
  File "c:\python37x64\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u3010' in position 0: character maps to <undefined>
Call stack:
  File "main.py", line 140, in <module>
  File "main.py", line 109, in main
  File "logging\__init__.py", line 1383, in info
  File "logging\__init__.py", line 1519, in _log
  File "logging\__init__.py", line 1529, in handle
  File "logging\__init__.py", line 1591, in callHandlers
  File "logging\__init__.py", line 905, in handle
  File "logging\__init__.py", line 1132, in emit
  File "logging\__init__.py", line 1040, in emit
Message: '【ZP】Sengoku period'
Arguments: ()
15:36:59 [INFO] : Spotted
15:36:59 [INFO] : 【ZP】Rice cultivating civilization【1.0】
--- Logging error ---
Traceback (most recent call last):
  File "logging\__init__.py", line 1037, in emit
  File "c:\python37x64\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u3010' in position 0: character maps to <undefined>
Call stack:
  File "main.py", line 140, in <module>
  File "main.py", line 109, in main
  File "logging\__init__.py", line 1383, in info
  File "logging\__init__.py", line 1519, in _log
  File "logging\__init__.py", line 1529, in handle
  File "logging\__init__.py", line 1591, in callHandlers
  File "logging\__init__.py", line 905, in handle
  File "logging\__init__.py", line 1132, in emit
  File "logging\__init__.py", line 1040, in emit
Message: '【ZP】Rice cultivating civilization【1.0】'
Arguments: ()
15:36:59 [INFO] : GlitterWorld Prime [Unstable]
15:36:59 [INFO] : ---LOG END---

15:37:00 [INFO] : The above log will be sent to the server if you want.
15:37:00 [INFO] : Help the developer improve the program by uploading a DB
log will collect :
 compare your mods with online DB, and get mods which are not on the DB

upload it? Y/N > y
15:38:19 [ERROR] : Critical Error occured while running...
15:38:19 [ERROR] : No module named 'requests'
15:38:19 [ERROR] : please report this to issue in github

**Comment by zzzz465** [comment]
my codes are going to be a spaghetti...

anyway, if the mod name includes an illegal character like "【", that will make an error.
I add code to avoid them. so it will work now fine.

**Comment by Emeranthil** [comment]
Alright so I've only just been able to test the new hotfix and it is still acting up. I believe before it shows the illegal characters properly, but now in my console window it just shows a box with a ? in it instead of the actual character for the sengoku period. Here's the new log

03:54:47 [INFO] : ---LOG START---
03:54:47 [INFO] : Floor Lights - 1.0
03:54:47 [INFO] : [SS]GhostArmy
03:54:47 [INFO] : GlitterWorld Prime [Unstable]
03:54:47 [INFO] : Mechalit Core 1.0
03:54:47 [INFO] : Mechalit Equipment + Faction 1.0
03:54:47 [INFO] : 【ZP】Sengoku period
--- Logging error ---
Traceback (most recent call last):
  File "logging\__init__.py", line 1037, in emit
  File "c:\python37x64\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u3010' in position 0: character maps to <undefined>
Call stack:
  File "main.py", line 144, in <module>
  File "main.py", line 110, in main
  File "logging\__init__.py", line 1383, in info
  File "logging\__init__.py", line 1519, in _log
  File "logging\__init__.py", line 1529, in handle
  File "logging\__init__.py", line 1591, in callHandlers
  File "logging\__init__.py", line 905, in handle
  File "logging\__init__.py", line 1132, in emit
  File "logging\__init__.py", line 1040, in emit
Message: '【ZP】Sengoku period'
Arguments: ()
03:54:47 [INFO] : Spotted
03:54:47 [INFO] : 【ZP】Rice cultivating civilization【1.0】
--- Logging error ---
Traceback (most recent call last):
  File "logging\__init__.py", line 1037, in emit
  File "c:\python37x64\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u3010' in position 0: character maps to <undefined>
Call stack:
  File "main.py", line 144, in <module>
  File "main.py", line 110, in main
  File "logging\__init__.py", line 1383, in info
  File "logging\__init__.py", line 1519, in _log
  File "logging\__init__.py", line 1529, in handle
  File "logging\__init__.py", line 1591, in callHandlers
  File "logging\__init__.py", line 905, in handle
  File "logging\__init__.py", line 1132, in emit
  File "logging\__init__.py", line 1040, in emit
Message: '【ZP】Rice cultivating civilization【1.0】'
Arguments: ()
03:54:47 [INFO] : ---LOG END---

**Comment by Emeranthil** [comment]
Update of the Error log since I've got more mods since the last post. Thanks for any help in advance.

17:47:19 [INFO] : ---LOG START---
17:47:19 [INFO] : Apex: Rimworld Legends test
17:47:19 [INFO] : Bargain Tweaks
17:47:19 [INFO] : BoomMod
17:47:19 [INFO] : Compare Tool
17:47:19 [INFO] : Cryptorestore Caskets (1.0)
17:47:19 [INFO] : DeepRim
17:47:19 [INFO] : Dubs Mint Minimap
17:47:19 [INFO] : ED-Prometheus
17:47:19 [INFO] : ED-ShieldsBasic
17:47:19 [INFO] : Electric Stonecutting Table
17:47:19 [INFO] : Floor Lights - 1.0
17:47:19 [INFO] : [XND] Genetically Engineered Plants
17:47:19 [INFO] : GeneticRim Cosmic Horrors Patch
17:47:19 [INFO] : GeneticRim Megafauna Patch
17:47:19 [INFO] : [SS]GhostArmy
17:47:19 [INFO] : Idle Power Consumption
17:47:19 [INFO] : [KV] Infinite Storage - 1.0
17:47:19 [INFO] : [Uru] Kemono Friends Hair (1.0)
17:47:19 [INFO] : LongRangePodLauncher
17:47:20 [INFO] : Mechalit Core 1.0
17:47:20 [INFO] : Mechalit Equipment + Faction 1.0
17:47:20 [INFO] : MiningCo. Alert speaker
17:47:20 [INFO] : MiningCo. MiningHelmet
17:47:20 [INFO] : Multiplayer
17:47:20 [INFO] : Power Logic
17:47:20 [INFO] : [XND] Profitable Weapons
17:47:20 [INFO] : Remote Doors
17:47:20 [INFO] : RimNGE
17:47:20 [INFO] : 【ZP】Sengoku period
--- Logging error ---
Traceback (most recent call last):
  File "logging\__init__.py", line 1037, in emit
  File "c:\python37x64\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u3010' in position 0: character maps to <undefined>
Call stack:
  File "main.py", line 144, in <module>
  File "main.py", line 110, in main
  File "logging\__init__.py", line 1383, in info
  File "logging\__init__.py", line 1519, in _log
  File "logging\__init__.py", line 1529, in handle
  File "logging\__init__.py", line 1591, in callHandlers
  File "logging\__init__.py", line 905, in handle
  File "logging\__init__.py", line 1132, in emit
  File "logging\__init__.py", line 1040, in emit
Message: '【ZP】Sengoku period'
Arguments: ()
17:47:20 [INFO] : Smarty Storyteller
17:47:20 [INFO] : Science Never Stops
17:47:20 [INFO] : Spotted
17:47:20 [INFO] : Storage Tweaks
17:47:20 [INFO] : [T] ExpandedCloth
17:47:20 [INFO] : [T] ExpandedCrops
17:47:20 [INFO] : [T] MiscStuff
17:47:20 [INFO] : [T] MoreBedsCloth
17:47:20 [INFO] : [T] RawCropThoughts
17:47:21 [INFO] : Resource Replicator (1.0)
17:47:21 [INFO] : [Uru] Touhou Hair (1.0)
17:47:21 [INFO] : Transfer Trait
17:47:21 [INFO] : [XND] Use That Sniper's Scope!
17:47:21 [INFO] : VGP Bulk Garden Drinks
17:47:21 [INFO] : VGP Garden Dyes
17:47:21 [INFO] : None
17:47:21 [INFO] : 【ZP】Rice cultivating civilization【1.0】
--- Logging error ---
Traceback (most recent call last):
  File "logging\__init__.py", line 1037, in emit
  File "c:\python37x64\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u3010' in position 0: character maps to <undefined>
Call stack:
  File "main.py", line 144, in <module>
  File "main.py", line 110, in main
  File "logging\__init__.py", line 1383, in info
  File "logging\__init__.py", line 1519, in _log
  File "logging\__init__.py", line 1529, in handle
  File "logging\__init__.py", line 1591, in callHandlers
  File "logging\__init__.py", line 905, in handle
  File "logging\__init__.py", line 1132, in emit
  File "logging\__init__.py", line 1040, in emit
Message: '【ZP】Rice cultivating civilization【1.0】'
Arguments: ()
17:47:21 [INFO] : Jernfalk's Paper Currency Mod
17:47:21 [INFO] : [v1.0] Jernfalk's Standalone Horses
17:47:21 [INFO] : ---LOG END---

**Comment by zzzz465** [comment]
change output method to python default, not logging.
this SHOULD work.

**Comment by zzzz465** [comment]
try v0.572, and also that version will include Linux support!

**Comment by Emeranthil** [comment]
I'm not sure how to change the output method as I've not really messed with python and such. I'll try to new version when I can and get back to you.
